### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by NokiaGuy** [roblox-linux-wrapper/roblox-linux-wrapper#117]
After reading the ```readme.md``` I installed the deb (github was being buggy so I couldn't install it from source) and it installed easily. However I cannot access any of the files now and ```roblox-linux-wrapper is not a valid directory```

Am I missing something? Ubuntu 14.04 Unity.

**Comment by GLolol** [comment]
What are you trying to do that gives you the "invalid directory" error?

**Comment by NokiaGuy** [comment]
cd roblox-linux-wrapper

**Comment by GLolol** [comment]
If you're using the `.deb` installation, you don't need to do anything related to Git. Just run Roblox Linux Wrapper as a normal app (just type `rlw` in the command line) or from your DE's application menu.

There was a typo in the Git installation instructions that I just fixed in a3bf2934927d829ccb24d2a74743263dca7c471a.

**Comment by NokiaGuy** [comment]
```
sam@bitsandbytes:~$ rlw
No command 'rlw' found, did you mean:
 Command 'rl' from package 'randomize-lines' (universe)
 Command 'r2w' from package 'rest2web' (universe)
 Command 'raw' from package 'util-linux' (main)
rlw: command not found
```

(after installing deb)

**Comment by GLolol** [comment]
Are you sure you installed it correctly? RLW's `.deb` installs the script into `/usr/bin`, so it should always be accessible in your PATH.
