### ISSUE TITLE
Can Not Move

### ISSUE THREAD

**Issue by stefanocorona12** [roblox-linux-wrapper/roblox-linux-wrapper#137]
I loaded a game, no graphical flashes. I haven't used this in a while. I push W as expected and it did not register as walking forward, nor the arrow keys work. I'll stick around and watch this thread

**Comment by GLolol** [comment]
That's strange, but at least you can load the game. ;(

Can you post the information mentioned in https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/blob/master/CONTRIBUTING.md#information-needed-in-a-bug-report?

**Comment by stefanocorona12** [comment]
Sorry, just read that. 

I am using Wine Version 1.7.44
Roblox Linux Wrapper 2015.06.16
Linux Mint 17.2 64-bit on Kernel 3.19.0-22-generic
Intel Graphics

I don't really have any errors.

**Comment by alfonsojon** [comment]
@stefanocorona12 Those Chromebooks work surprisingly well as Linux laptops. Given that the game loads, can you tell me what window manager you're using? If you are not sure, just tell me the desktop environment (i.e. Unity, XFCE, GNOME Shell, MATE, KDE, and so on...). I have a feeling this may be a window manager issue.

**Comment by stefanocorona12** [comment]
I was using Cinnamon desktop (plus Numix Circle if that helps). When I tried this a couple years ago while this was a script you copied/pasted into a Terminal, it worked fine in Unity.

**Comment by RobloxTechnicalSupport** [comment]
This is very simple. It could be an in game issue where your avatar gets stuck in another when you spawn, i have also had wires start slipping out of the back of my keyboard and keys would not work, or a very unlikely issue is that the usb card thats connected to the computer has its own data just like that mother board and every other chip. There is a chance a very small chance the script or coding that lets the mother board use the usb hub to have a keyboard to control certain applications like Roblox isn't working in that area or in simple terms the entire thing is basically fried and you mint want to either reinstall Linux or witch to windows cause remember a lot of Linux is beta and a lot of random people make the operating systems for Linux that's why it's also so cheap to buy.

**Comment by GLolol** [comment]
@RobloxTechnicalSupport This has absolutely nothing to do with the issue. If keys stopped working outside of Wine, I think the submitter would've noticed.

Can you prove that you're actually affiliated with ROBLOX? Your name is otherwise *really* misleading.

**Comment by stefanocorona12** [comment]
@RobloxTechnicalSupport

> witch to Windows

Nice meme m8
