### ISSUE TITLE
Is it working with WINE 3.0?

### ISSUE THREAD

**Issue by fantoro** [roblox-linux-wrapper/roblox-linux-wrapper#177]
I really want to play it on Linux because I have a shitty hard drive so booting into Windows is worse than torture.

**Comment by alfonsojon** [comment]
No, it is not working on Wine 3.0, unfortunately. I tried it and it kicks users from the server the same way. I think they're either kicking the client because it detects a non-genuine version of Windows or something regarding their anti cheat system kicks the user. Either way, the game is still unplayable online. Sorry!
