### ISSUE TITLE
Not allowing me to play roblox

### ISSUE THREAD

**Issue by poshy1** [roblox-linux-wrapper/roblox-linux-wrapper#197]
wine closed unsuccessfully.
See terminal for details. (exit code 1)

**Comment by Username404-59** [comment]
First, you should've read the README, as of today it is possible again to play roblox on linux but you need wine 6.11 and a special patch to fix a mouse issue, and roblox-linux-wrapper has been very inactive to i'd reccomend you https://gitlab.com/brinkervii/grapejuice since prebuilds are available in the discord server of grapejuice: https://discord.gg/mRTzEb6

**Comment by alfonsojon** [comment]
Can you provide more detail about the issue? What triggers it? How did it happen?

**Comment by poshy1** [comment]
I don't know how it happened, i think i closed roblox to early or something and after that i couldn't play
